### ISSUE TITLE
Swapping players between teams after initial drafting appears to be broken (trading page)

### ISSUE THREAD

**Issue by emmatracy** [andyjparedes/fifa_dream_team_testing#10]
Description: when we tried swapping players after drafting the maximum and minimum number of players, players were frequently duplicated or swapped incorrectly for the wrong player. It appears that swapping players on the trading page often doesn’t work properly.
Severity: High
Examples:
[https://imgur.com/a/Py4oY73](https://imgur.com/a/Py4oY73)

**Comment by andyjparedes** [comment]
Fixed
