### ISSUE TITLE
Unclear how to do real-time updating of drafted players

### ISSUE THREAD

**Issue by emmatracy** [andyjparedes/fifa_dream_team_testing#14]
Description: It is not clear how to do real-time updating of drafted players to allow for formation changes. Click, double-click, and drag were attempted on the drafted players box. It is also not clear whether or not this is implemented.
Severity: Medium (if unclear), High (if unimplemented)
<img width="623" alt="Screen Shot 2019-12-04 at 4 03 16 PM" src="https://user-images.githubusercontent.com/17819478/70185530-97cb6a80-16af-11ea-9bf6-439240a24a1a.png">

**Comment by andyjparedes** [comment]
Not meant to interact with
