### ISSUE TITLE
UX Review

### ISSUE THREAD

**Issue by worzalla** [andyjparedes/fifa_dream_team_testing#17]
As noted, usability is a main feature for iteration 3. Comments on this are included in the following

![Resulting Page](https://user-images.githubusercontent.com/32086960/70206898-9c634380-16ee-11ea-91bc-c2bc17fb51f8.png)
![Trading Page](https://user-images.githubusercontent.com/32086960/70206899-9c634380-16ee-11ea-8b65-9c94aea77532.png)
![Drafting Page](https://user-images.githubusercontent.com/32086960/70206900-9c634380-16ee-11ea-88a5-f6aac9191031.png)
![Beginning Page](https://user-images.githubusercontent.com/32086960/70206901-9c634380-16ee-11ea-9ce6-7f41fdcfc11d.png)

Severity: High

**Comment by andyjparedes** [comment]
Comments on Draft Page still to be resolved
