### ISSUE TITLE
UX drafting a player

### ISSUE THREAD

**Issue by emmatracy** [andyjparedes/fifa_dream_team_testing#3]
Description : Not intuitive for how a player is drafted. Took a few minutes to discover you had to double click a player. It is also annoying to drag your mouse from the left, where you double click on a player to add them and then have to drag your mouse to the middle of the screen to confirm. 
Suggestions : It may be beneficial to reconsider the UX for this page, possibly include a drop down under player when clicked once. At least write instructions.
Severity : moderate

**Comment by andyjparedes** [comment]
Fixed
