### ISSUE TITLE
Trading page is inaccessible

### ISSUE THREAD

**Issue by emmatracy** [andyjparedes/fifa_dream_team_testing#4]
Description: After drafting a few players the page refreshes/redirects to /tradingpage.html but has the same functionality as the drafting page
Comments: We had this issue when we built the page from npm. It seems like there are default variables being used because there’s nothing to select an amount of teams. Additionally it may be beneficial to use React Navigation (https://reactnavigation.org/) or React Router Dom to route users. 
Severity: High

**Comment by andyjparedes** [comment]
Fixed
