### ISSUE TITLE
UX Reposition Drafting Page button to somewhere more easily visible.

### ISSUE THREAD

**Issue by emmatracy** [andyjparedes/fifa_dream_team_testing#8]
Description: Make the button at the bottom, and make it much more easily visible. Make it clear that after the form is completed, this button should be pressed.
Severity: Low
[
<img width="623" alt="Screen Shot 2019-12-04 at 3 46 14 PM" src="https://user-images.githubusercontent.com/17819478/70184317-36a29780-16ad-11ea-9dc2-995983bdad5b.png">
](url)

**Comment by andyjparedes** [comment]
This is in the video example
