### ISSUE TITLE
Errors displayed on the initial page output two alerts

### ISSUE THREAD

**Issue by emmatracy** [andyjparedes/fifa_dream_team_testing#9]
Description: If you leave the number of teams blank, then click Drafting page, you get two alerts instead of just one.
Severity: Low
<img width="279" alt="Screen Shot 2019-12-04 at 3 47 11 PM" src="https://user-images.githubusercontent.com/17819478/70184391-58038380-16ad-11ea-9a3f-1e67437ebed9.png">

**Comment by andyjparedes** [comment]
Fixed
